#!/bin/bash

# RUN back-end

echo "RUN back-end:"

# RUN bank
( 
    cd back-end/bank; 
    cat .env.example > .env;
    docker run --rm \
        -u "$(id -u):$(id -g)" \
        -v $(pwd):/var/www/html \
        -w /var/www/html \
        laravelsail/php81-composer:latest \
        composer install --ignore-platform-reqs;
    ./vendor/bin/sail up -d;
    ./vendor/bin/sail php artisan migrate;
)
# Fake data: ./vendor/bin/sail php artisan migrate --seed
# Delete migrations: ./vendor/bin/sail php artisan migrate:reset

# RUN catalog
(
	cd back-end/catalog;
	./build_catalog.sh
)


# RUN recipe
(
	cd back-end/recipe;
	./build_recipe.sh
)


# RUN front-end

echo -e "\nRUN front-end:"

( cd front-end ; docker-compose up -d )


