version: '3'

volumes:
  postgres:

services:
  db_ingridients:
    image: 'postgres:13.1-alpine'
    container_name: db_ingridients
    env_file:
      - .env
    ports:
      - "5401:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./src/main/resources/db-migrations/v-1.0-sql-migrations/initial-schema-import.sql:/docker-entrypoint-initdb.d/create_tables.sql

  app_catalog:
    image: 'ingridient-catalog'
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app_catalog
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - db_ingridients

networks:
  dishes_host:
    driver: bridge
