version: '3'

volumes:
  postgres:

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ingridients
    ports:
      - "5400:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    image: 'ingridient-catalog'
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
