version: '3.9'

volumes:
  postgres:
    name: store

services:
  db:
    image: postgres:13
    container_name: store
    restart: always
    env_file:
      - .env
    ports:
      - 6161:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3000:3000'
    restart: always
